services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: showcode-backend
    env_file: ./backend/.env
    volumes:
      - ./rsa_public.pem:/app/rsa_public.pem
    networks:
      - showcode
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`showcode.parthajeet.xyz`) && (PathPrefix(`/analyze`) || PathPrefix(`/.well-known`))"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=tuberesolver"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: showcode-frontend
    depends_on:
      - backend
    networks:
      - showcode
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`showcode.parthajeet.xyz`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=tuberesolver"

networks:
  showcode:
    external: true
    driver: bridge

